language: scala

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

env:
  global:
    - PUBLISH=true

script:
  - sbt ++$TRAVIS_SCALA_VERSION test